# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex', '0004_auto_20160916_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='processed_spider',
            field=models.BooleanField(default=False),
        ),
    ]
