# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex', '0006_source_ready_for_crawling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='processed_spider',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
