# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex', '0007_auto_20160918_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='processed_spider',
            field=models.CharField(default=b'', max_length=50, null=True),
        ),
    ]
