# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex', '0008_auto_20160918_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='processed_spider',
            field=models.CharField(blank=True, default=b'', max_length=50),
        ),
    ]
